apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: apigateway
  name: apigateway-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: apigateway
  type: LoadBalancer
status:
  loadBalancer: {}