apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: lowercase
  name: lowercase-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: lowercase
status: {}